version: '3'
services:
  web:
    image: dane-video-segmentation-worker:latest
    volumes:
      - ./data:/data
      - ./config:/root/.DANE
    container_name: visxp
    command: --run-test-file  # NOTE: comment this line to spin up th worker
    logging:
      options:
        max-size: 20m
    restart: always