# Important for understanding DANE configs: https://github.com/CLARIAH/DANE/blob/main/DANE/config.py

# Important note:
# FIRST the home dir config is applied (~/.DANE/config.yml),
# THEN the base_config.yml will overwrite anything,
# THEN the local config.yml

#Note: For local testing, copy this file to config.yml (in main dir of this repo)
RABBITMQ:
    HOST: dane-rabbitmq-api.default.svc.cluster.local
    PORT: 5672
    EXCHANGE: DANE-exchange
    RESPONSE_QUEUE: DANE-response-queue
    USER: guest # change this for production mode
    PASSWORD: guest # change this for production mode
ELASTICSEARCH:
    HOST:
        - elasticsearch
    PORT: 9200
    USER: '' # change this for production mode
    PASSWORD: '' # change this for production mode
    SCHEME: http
    INDEX: dane-index-k8s-asr
FILE_SYSTEM:
    BASE_MOUNT: /data # data when running locally
    INPUT_DIR: input-files
    OUTPUT_DIR: output-files/visxp_prep
PATHS:
    TEMP_FOLDER: /data/input-files
    OUT_FOLDER: /data/output-files
VISXP_PREP:
    RUN_HECATE: true
    RUN_KEYFRAME_EXTRACTION: true
    RUN_AUDIO_EXTRACTION: true
    SPECTOGRAM_WINDOW_SIZE_MS: 1000
    SPECTOGRAM_SAMPLERATE_HZ:
        - 24000
    TEST_INPUT_FILE: https://openbeelden.nl/files/13/66/1411058.1366653.WEEKNUMMER404-HRE000042FF_924200_1089200.mp4
    # TEST_INPUT_FILE: s3://your-bucket/assets/your-test-video.mp4
    # TEST_INPUT_FILE: /data/your-test-video.mp4
INPUT:
    DELETE_ON_COMPLETION: False  # NOTE: set to True in production environment
OUTPUT:
    DELETE_ON_COMPLETION: True
    TRANSFER_ON_COMPLETION: True
    S3_ENDPOINT_URL: https://s3.eu-west-1.amazonaws.com/
    S3_BUCKET: beng-daan-visxp  # bucket reserved for 1 type of output
    S3_FOLDER_IN_BUCKET: assets  # folder within the bucket
DANE_DEPENDENCIES:
    - DOWNLOAD