name: Build image (with docker cache) and push to ECR

on:
  workflow_call:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to ECR
        uses: docker/login-action@v3
        with:  # https://github.com/docker/login-action#aws-elastic-container-registry-ecr
          registry: 917951871879.dkr.ecr.eu-west-1.amazonaws.com
          username: ${{ secrets.AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          # context: .
          # file: ./Dockerfile
          push: true  # https://docs.docker.com/build/ci/github-actions/manage-tags-labels/ (TODO check later)
          tags: "917951871879.dkr.ecr.eu-west-1.amazonaws.com/dane-video-segmentation-worker:latest"
          cache-from: type=gha
          cache-to: type=gha,mode=max
