name: Manual deploy

on:
  workflow_dispatch:
    inputs:
      target:
        type: choice
        required: true
        default: ghcr
        options:
        - ghcr

jobs:
  deploy:
    uses: ./.github/workflows/_deploy.yml
    secrets: inherit
    with:
      target: ${{ inputs.target }}
